// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAXa3O0yV8PfcLwI0Qtx5YegIdnsZQJbA',
    appId: '1:856351497483:android:dfc8887a90ebc03e82d60e',
    messagingSenderId: '856351497483',
    projectId: 'bikes-b6d74',
    storageBucket: 'bikes-b6d74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0YRzAgGeE56YD7UxkuICrQA24gg_Fjxc',
    appId: '1:856351497483:ios:dc5ca7ccc37cf6f482d60e',
    messagingSenderId: '856351497483',
    projectId: 'bikes-b6d74',
    storageBucket: 'bikes-b6d74.firebasestorage.app',
    iosBundleId: 'com.example.bikers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6R9bXyCX0vJaHLX_H1ftLlUYv6jeQJcI',
    appId: '1:856351497483:web:946305e489aeff0082d60e',
    messagingSenderId: '856351497483',
    projectId: 'bikes-b6d74',
    authDomain: 'bikes-b6d74.firebaseapp.com',
    storageBucket: 'bikes-b6d74.firebasestorage.app',
    measurementId: 'G-G8S8HV6H37',
  );
}
